# -*- coding: utf-8 -*-
"""kadai_005.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eQIkyKQPfL3AFe_QnP6kDFFoZP7Uzdy_
"""

#matplotlib.pyplotメソッドとをインポートするコードを記述する。
import matplotlib.pyplot as plt
#numpyをインポートするコードを記述する。
import numpy as np

#Figure(描画領域全体)とAxes(ひとつひとつのプロットを描く領域)を作成するコードを記述する。
fig, axes = plt.subplots(2, 3, tight_layout = True)

#各領域に、折れ線グラフ、sin関数、ヒストグラム、散布図のデータを表示するコードを記述する。

##axes[0, 0]
x0 = [1, 2, 3, 4]
y0 = [1, 2, -5, 2]
axes[0,0].plot(x0, y0)

##axes[0, 1]
# データを作成
# 0から10までの幅で配列を等間隔に100個作成する
x1 = np.linspace(0, 10, 100)
y1 = 2 + 2 * np.sin(2 * x1)
# プロット
axes[0,1].plot(x1, y1, linewidth=2.0)
ax.set(xlim=(0, 10), xticks=np.arange(0, 10),
       ylim=(-1, 5), yticks=np.arange(-1, 6))

##axes[0, 2]
# 平均が15, 標準偏差5の標準正規分布から2000個の乱数の生成する
x3 = np.random .normal(15, 5, 2000)
plt.xlim(-10, 40)
# ヒストグラムをプロット
axes[0, 2].hist(x3, bins=30)

##axes[1, 0]
# データを生成する
np.random.seed(3)
x4 = 4 + np.random.normal(0, 2, 60)
y4 = 4 + np.random.normal(0, 2, len(x4))
# プロットする
axes[1, 0].scatter(x4, y4)

#結果を表示する。
plt.show()