# -*- coding: utf-8 -*-
"""kadai_003.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fJiADw0DcHhVJ7316mE8OmhNkvFUjTyC
"""

#NumPyをインポートするコードを記述する
import numpy as np

#AとBの行列を格納する多次元配列のコードを記述する
A = np.array([[0, 1],[2, 3],[4, 5]])
B = np.array([[0,1, 2, 3], [4, 5, 6, 7]])

#行列の積の計算をするコードを記述する
#Step3.の計算結果を表示するコードを記述する
AB = np.dot(A, B)
AB

#行列の要素の最大値を求めるコードを記述する
AB.max()